env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10.1
      script: xcodebuild -project Tests/UnitTests.xcodeproj -scheme "iOS Tests" -sdk iphonesimulator
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test

